apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyeur-consumer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voyeur-consumer
  template:
    metadata:
      labels:
        app: voyeur-consumer
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: voyeur-consumer
        image: papakao/voyeur-consumer:latest
        command: ["python"]
        args: ["-u", "/app/consumer.py"]
        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_QUEUE_VOYEUR
          value: "increment_queue"
        - name: API_URL
          value: "http://voyeur/voyeur/increment/"
